"""Push a job's local git repo to GitHub (new or existing repo), optionally open a PR.

Routes:
  GET    /api/github                 connection status (never the token)
  PUT    /api/github/token {token}   validate via GET /user and store (server-side, Mongo)
  DELETE /api/github                 disconnect (token removed)
  PUT    /api/github/settings        {auto_push: {enabled, private}, oauth_client_id}
  POST   /api/github/oauth/start     OAuth device flow: get a user code + verification URL
  POST   /api/github/oauth/poll      exchange the device code (call every `interval` s)
  POST   /api/github/oauth/cancel    abandon the pending device flow

OAuth and personal access tokens are mutually exclusive: connecting one while the other is
active (or while a device flow is pending) is a 409; disconnect first.
  GET    /api/github/repos?q=        the user's repositories (searchable)
  GET    /api/jobs/{id}/github       defaults for the push dialog + last push + watches
  POST   /api/jobs/{id}/github/push  push (and optionally open a PR)
  GET    /api/github/watches         what the poller is watching
  POST   /api/github/poll            poll GitHub now (otherwise every R2A_GITHUB_POLL_SECONDS)

Never force-pushes: a branch that exists on GitHub with different history is reported as a
conflict. The token reaches git only as an http.<host>.extraHeader passed through GIT_CONFIG_*
environment variables of one git process - never argv, the remote URL or .git/config - and all
git output is redacted. After a push a watch polls the branch, PR and CI with conditional
requests and emits github_* notifications (no public URL or webhook needed). The poller lives
in-process: keep uvicorn at --workers 1.
"""
from __future__ import annotations

import asyncio
import base64
import logging
import os
import re
import time
from datetime import datetime, timedelta, timezone
from urllib.parse import quote, urlparse

import httpx
from fastapi import APIRouter, HTTPException, Query
from pydantic import BaseModel, Field

import git_cli
import git_integration
import github_client as ghc
import notifier
import repos
from database import db as default_db
from github_client import GitHub, GitHubError, redact
from orchestrator import append_log, now_iso

router = APIRouter(prefix="/api")
logger = logging.getLogger("roadmap2arena.github")
REPO_PAGES = 3  # up to 300 repositories in the picker
PR_BODY_MAX = 60_000
PUSH_TIMEOUT = 300
WATCH_DAYS = 7
NO_CI_GRACE = timedelta(minutes=15)   # "no CI configured" is only final this long after the push
RATE_FLOOR = 50                       # pause polling when fewer API calls than this remain


def poll_seconds() -> int:
    try:
        return max(30, int(os.environ.get("R2A_GITHUB_POLL_SECONDS") or 60))
    except ValueError:
        return 60


# ------------------------------------------------------------------ helpers
def slugify(text: str, fallback: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", (text or "").lower()).strip("-")[:40].strip("-")
    return slug or fallback


def defaults_for(job: dict, steps: list[dict]) -> dict:
    slug = slugify(job.get("title") or "", f"job-{job['id'][:8]}")
    title = job.get("title") or f"ROADMAP2ARENA job {job['id'][:8]}"
    checklist = "\n".join(f"- [{'x' if s['status'] == 'done' else ' '}] Step {s['index']}: {s['title']}" for s in steps)
    body = (f"Generated by ROADMAP2ARENA from job `{job['id']}` "
            f"({job.get('steps_done', 0)}/{job.get('step_total', len(steps))} steps done, model `{job.get('model')}`).\n\n"
            f"## Steps\n{checklist}\n")
    roadmap = (job.get("roadmap_md") or "").strip()
    if roadmap:
        body += f"\n<details><summary>Roadmap</summary>\n\n{roadmap}\n\n</details>\n"
    return {"repo_name": slug, "branch": f"r2a/{slug}", "pr_title": title, "pr_body": body[:PR_BODY_MAX]}


def _allowed_hosts() -> set[str]:
    host = urlparse(ghc.api_url()).hostname or ""
    return {"github.com"} if host == "api.github.com" else {host}


def check_clone_url(url: str) -> str:
    """Only push to GitHub over https (local paths are allowed for tests via an env flag)."""
    p = urlparse(url or "")
    if p.scheme == "https" and p.hostname in _allowed_hosts():
        return url
    if os.environ.get("R2A_GITHUB_ALLOW_FILE_REMOTES") == "1" and (p.scheme == "file" or (url or "").startswith("/")):
        return url
    raise GitHubError(502, f"GitHub returned an unexpected clone URL ({p.scheme or 'no scheme'}://{p.hostname or ''})")


def auth_env(login: str, token: str, host: str) -> dict:
    """http.<host>.extraHeader via GIT_CONFIG_* env vars: not in argv (ps), the URL or .git/config, and
    only sent to that host. The first (empty) value resets any inherited extraHeader list."""
    basic = base64.b64encode(f"{login}:{token}".encode()).decode()
    key = f"http.{host}.extraHeader"
    return {"GIT_CONFIG_COUNT": "3", "GIT_CONFIG_KEY_0": key, "GIT_CONFIG_VALUE_0": "",
            "GIT_CONFIG_KEY_1": key, "GIT_CONFIG_VALUE_1": f"Authorization: Basic {basic}",
            "GIT_CONFIG_KEY_2": "credential.helper", "GIT_CONFIG_VALUE_2": "", "GIT_TERMINAL_PROMPT": "0"}


def classify_push(output: str) -> str:
    low = output.lower()
    if "non-fast-forward" in low or "fetch first" in low or "stale info" in low or "[rejected]" in low:
        return "non_fast_forward"
    if "workflow" in low and ("scope" in low or "permission" in low):
        return "workflow_permission"
    if "could not read username" in low or "authentication failed" in low or "invalid username or token" in low:
        return "auth"
    if "repository not found" in low:
        return "not_found"
    if ("permission to" in low and "denied" in low) or "error: 403" in low or "returned error: 403" in low:
        return "forbidden"
    if "gh013" in low or "protected branch" in low or "rule violations" in low or "gh006" in low:
        return "rules"
    if "timed out" in low:
        return "timeout"
    return "failed"


def push_status(kind: str, branch: str) -> tuple[int, str]:
    return {
        "non_fast_forward": (409, f"The branch '{branch}' already exists on GitHub with different commits. Choose another "
                                  "branch name - ROADMAP2ARENA never force-pushes."),
        "workflow_permission": (403, "Pushing .github/workflows files needs the 'workflow' scope (classic) or "
                                     "'Workflows: write' (fine-grained)."),
        "auth": (401, "GitHub rejected the token during git push - reconnect GitHub in Settings."),
        "not_found": (404, "git push: repository not found, or the token has no access to it."),
        "forbidden": (403, "GitHub refused the push - the token has no write access to this repository "
                           "(classic: 'repo' scope; fine-grained: Contents read/write)."),
        "rules": (409, f"The branch '{branch}' is protected by branch protection / repository rules - choose another "
                       "branch name."),
        "timeout": (504, f"git push timed out after {PUSH_TIMEOUT}s."),
        "failed": (502, "git push failed."),
    }[kind]


def push_sync(root: str, url: str, branch: str, token: str, login: str = "x-access-token",
              timeout: float = PUSH_TIMEOUT) -> None:
    p = urlparse(url)
    host = f"{p.scheme}://{p.hostname}{f':{p.port}' if p.port else ''}/" if p.scheme in ("http", "https") else "https://github.com/"
    env = auth_env(login or "x-access-token", token, host)
    secrets = (token, env["GIT_CONFIG_VALUE_1"].split()[-1])  # the token and its base64 form
    try:
        proc = git_cli.run(root, "push", "--porcelain", "--no-verify", "--", url, f"HEAD:refs/heads/{branch}",
                           env=env, timeout=timeout, check=False)
    except git_cli.GitError as exc:
        out = redact(f"{exc} {getattr(exc, 'stderr', '') or ''}", *secrets)
        code, hint = push_status(classify_push(out), branch)
        raise GitHubError(code, f"{hint} git: {out.strip()[-400:]}") from None
    if proc.returncode == 0:
        return
    out = redact(proc.stderr.decode("utf-8", "replace") + proc.stdout.decode("utf-8", "replace"), *secrets).strip()
    code, hint = push_status(classify_push(out), branch)
    raise GitHubError(code, f"{hint} git: {out[-400:] or f'exit {proc.returncode}'}")


def _http_error(e: GitHubError) -> HTTPException:
    headers = {"Retry-After": str(e.retry_after)} if e.retry_after else None
    return HTTPException(status_code=e.status, detail=e.message, headers=headers)


async def _token_or_409(db) -> str:
    token = await ghc.get_token(db)
    if not token:
        err = ghc.public(await ghc.get_doc(db)).get("token_error")
        raise HTTPException(status_code=409, detail=err or "GitHub is not connected - connect it in Settings > GitHub")
    return token


def _repo_summary(r: dict) -> dict:
    perms = r.get("permissions") or {}
    return {"full_name": r.get("full_name"), "name": r.get("name"), "owner": (r.get("owner") or {}).get("login"),
            "private": bool(r.get("private")), "default_branch": r.get("default_branch"),
            "html_url": r.get("html_url"), "description": r.get("description"),
            "can_push": bool(perms.get("push", perms.get("admin", False))), "updated_at": r.get("updated_at")}


# ------------------------------------------------------------------ core push
class PushRequest(BaseModel):
    mode: str = Field("new", pattern="^(new|existing)$")
    repo_name: str | None = None          # mode=new
    private: bool = True                  # mode=new
    description: str | None = Field(None, max_length=350)
    repo_full_name: str | None = None     # mode=existing, "owner/name"
    branch: str | None = None
    open_pr: bool = False
    pr_base: str | None = None
    pr_title: str | None = Field(None, max_length=256)
    pr_body: str | None = Field(None, max_length=PR_BODY_MAX)


async def push_job(db, job_id: str, body: PushRequest, source: str = "manual") -> dict:
    """Push the job repo to GitHub. Raises GitHubError / HTTPException with clear messages."""
    token = await _token_or_409(db)
    job = await db.jobs.find_one({"id": job_id}, {"_id": 0, "log": 0})
    if not job:
        raise HTTPException(status_code=404, detail=f"Job {job_id} not found")
    if job["status"] == "running":
        raise HTTPException(status_code=409, detail="The job is running - wait until it finishes (or stop it), then push")
    steps = await db.steps.find({"job_id": job_id}, {"_id": 0, "index": 1, "title": 1, "status": 1}).sort("index", 1).to_list(None)
    d = defaults_for(job, steps)
    branch = (body.branch or d["branch"]).strip()
    if not git_cli.valid_branch(branch):
        raise HTTPException(status_code=422, detail=f"'{branch}' is not a valid branch name")
    if body.mode == "new":
        name = (body.repo_name or d["repo_name"]).strip()
        if not ghc.REPO_NAME_RE.match(name) or name in (".", "..") or name.lower().endswith(".git"):
            raise HTTPException(status_code=422, detail="Repository name may only contain letters, digits, '.', '-' "
                                                        "and '_' (max 100) and must not end in .git")
        if body.open_pr:
            raise HTTPException(status_code=422, detail="A new repository has no base branch to open a pull request "
                                                        "against - push it first, then open PRs on later pushes")
    else:
        full = (body.repo_full_name or "").strip()
        if not ghc.FULL_NAME_RE.match(full):
            raise HTTPException(status_code=422, detail="repo_full_name must look like owner/repository")
    if body.pr_base is not None and body.pr_base.strip() and not git_cli.valid_branch(body.pr_base.strip()):
        raise HTTPException(status_code=422, detail=f"'{body.pr_base}' is not a valid base branch name")

    try:
        synced = await git_integration.sync_job(db, job_id)
    except git_cli.GitError as exc:
        raise HTTPException(status_code=500, detail=f"Could not prepare the local repository: {exc}")
    repo_doc = synced["repo"]
    if not repo_doc.get("head"):
        raise HTTPException(status_code=409, detail="The job's repository has no commits yet - nothing to push")
    root = repos.abs_path(repo_doc)

    login = ((await ghc.get_doc(db)) or {}).get("username") or "x-access-token"
    async with GitHub(token) as gh:
        created = False
        if body.mode == "new":
            try:
                resp = await gh.request("POST", "/user/repos", "create the repository", json={
                    "name": name, "private": body.private, "auto_init": False,
                    "description": body.description or f"Generated by ROADMAP2ARENA: {job.get('title') or ''}"[:350]})
            except GitHubError as e:
                if e.gh_status == 422 and "already exists" in e.message.lower():
                    raise GitHubError(409, f"A repository named '{name}' already exists in your account - choose "
                                           "another name or pick it under 'Existing repository'.")
                raise
            gh_repo, created = resp.json(), True
        else:
            gh_repo = (await gh.request("GET", f"/repos/{full}", f"find the repository {full}")).json()
            perms = gh_repo.get("permissions") or {}
            if perms and not (perms.get("push") or perms.get("admin")):
                raise GitHubError(403, f"Your token has no push access to {full}.")
        url = check_clone_url(gh_repo.get("clone_url", ""))
        html = gh_repo.get("html_url") or ""
        async with repos.lock_for(root):
            head = git_cli.out(root, "rev-parse", "HEAD").strip()
            await asyncio.to_thread(push_sync, root, url, branch, token, login)

        pr, pr_error = None, None
        if body.open_pr:
            base = (body.pr_base or "").strip() or gh_repo.get("default_branch") or "main"
            if base == branch:
                pr_error = "The base branch is the pushed branch - nothing to compare"
            else:
                try:
                    r = await gh.request("POST", f"/repos/{gh_repo['full_name']}/pulls", "open the pull request", json={
                        "title": (body.pr_title or d["pr_title"])[:256], "body": body.pr_body if body.pr_body is not None else d["pr_body"],
                        "head": branch, "base": base})
                    p = r.json()
                    pr = {"number": p.get("number"), "html_url": p.get("html_url"), "existing": False, "base": base,
                          "state": p.get("state", "open")}
                except GitHubError as e:
                    low = e.message.lower()
                    if "already exists" in low:
                        owner = gh_repo["full_name"].split("/")[0]
                        try:
                            r = await gh.request("GET", f"/repos/{gh_repo['full_name']}/pulls", "find the open pull request",
                                                 params={"head": f"{owner}:{branch}", "state": "open"})
                            items = r.json()
                            if items:
                                pr = {"number": items[0].get("number"), "html_url": items[0].get("html_url"),
                                      "existing": True, "base": items[0].get("base", {}).get("ref", base),
                                      "state": items[0].get("state", "open")}
                        except GitHubError:
                            pass
                        if not pr:
                            pr_error = "A pull request for this branch already exists"
                    elif "no history in common" in low:
                        pr_error = (f"Pushed, but no PR: '{branch}' has no history in common with '{base}' (the job "
                                    "repository started from scratch). Open a PR manually after merging histories.")
                    elif "no commits between" in low:
                        pr_error = f"Pushed, but no PR: there are no commits between '{base}' and '{branch}'."
                    elif e.gh_status == 422 and "base" in low:
                        pr_error = f"Pushed, but no PR: the base branch '{base}' does not exist."
                    else:
                        pr_error = f"Pushed, but the pull request failed: {e.message}"

    full_name = gh_repo.get("full_name")
    ts = now_iso()
    result = {
        "pushed": True, "source": source, "pushed_at": ts, "branch": branch, "head": head,
        "commit_count": repo_doc.get("commit_count"),
        "repo": {"full_name": full_name, "html_url": html, "private": bool(gh_repo.get("private")), "created": created},
        "branch_url": f"{html}/tree/{quote(branch, safe='/')}" if html else None,
        "commit_url": f"{html}/commit/{head}" if html else None,
        "pr": pr, "pr_error": pr_error,
    }
    remote = {"provider": "github", "full_name": full_name, "html_url": html, "clone_url": url, "branch": branch,
              "private": bool(gh_repo.get("private")), "pushed_head": head, "pushed_at": ts,
              "pr_url": pr["html_url"] if pr else None, "pr_number": pr["number"] if pr else None}
    await db.repos.update_one({"id": repo_doc["id"]}, {"$pull": {"remotes": {"provider": "github", "full_name": full_name, "branch": branch}}})
    await db.repos.update_one({"id": repo_doc["id"]}, {"$push": {"remotes": remote}})
    await db.jobs.update_one({"id": job_id}, {"$set": {"github": result}})
    what = "auto-pushed" if source == "auto" else "pushed"
    await append_log(db, job_id, "ok", f"GitHub: {what} {repo_doc.get('commit_count')} commits to {full_name} "
                                       f"branch {branch}{' (new repository)' if created else ''}")
    if pr:
        await append_log(db, job_id, "ok", f"GitHub: pull request #{pr['number']}{' (already open)' if pr['existing'] else ''} {pr['html_url']}")
    if pr_error:
        await append_log(db, job_id, "warn", f"GitHub: {pr_error}")
    await upsert_watch(db, job_id, full_name, html, branch, head, pr)
    await _notify(db, "github_pushed", job_id, f"{'Auto-pushed' if source == 'auto' else 'Pushed'} "
                  f"{repo_doc.get('commit_count')} commits to {full_name}:{branch} ({head[:7]})", result["branch_url"])
    if pr and not pr["existing"]:
        await _notify(db, "github_pr_opened", job_id, f"Opened PR #{pr['number']} in {full_name}", pr["html_url"])
    return result


async def on_job_finished(db, job_id: str, status: str) -> None:
    """Auto-push on completion (if enabled): to the job's last pushed repo/branch, else a new repo."""
    if status != "done":
        return
    doc = await ghc.get_doc(db)
    if not doc or not (doc.get("auto_push") or {}).get("enabled") or not await ghc.get_token(db):
        return
    job = await db.jobs.find_one({"id": job_id}, {"_id": 0, "github": 1, "title": 1})
    last = (job or {}).get("github")
    if last and last.get("repo", {}).get("full_name"):
        req = PushRequest(mode="existing", repo_full_name=last["repo"]["full_name"], branch=last["branch"])
    else:
        name = slugify((job or {}).get("title") or "", "r2a")[:60] + f"-{job_id[:6]}"
        req = PushRequest(mode="new", repo_name=name, private=bool(doc["auto_push"].get("private", True)))
    try:
        await push_job(db, job_id, req, source="auto")
    except (GitHubError, HTTPException) as exc:
        msg = exc.message if isinstance(exc, GitHubError) else exc.detail
        logger.warning("auto-push of job %s failed: %s", job_id, msg)
        await append_log(db, job_id, "warn", f"GitHub: auto-push failed - {msg}")
    except Exception as exc:  # noqa: BLE001 - never break anything after a job
        logger.exception("auto-push of job %s crashed", job_id)
        await append_log(db, job_id, "warn", f"GitHub: auto-push failed - {type(exc).__name__}")


# ------------------------------------------------------------------ routes
class TokenBody(BaseModel):
    token: str


class AutoPush(BaseModel):
    enabled: bool | None = None
    private: bool | None = None


class GitHubSettings(BaseModel):
    auto_push: AutoPush | None = None
    oauth_client_id: str | None = None   # "" clears the saved client ID (falls back to .env)


@router.get("/github")
async def get_github():
    return await ghc.status(default_db)


def _exclusive(doc: dict | None, wanted: str) -> None:
    """409 if the OTHER connection method is active (or, for a PAT, a device flow is pending).

    Replacing a PAT with another PAT is allowed; starting OAuth while OAuth is connected is a 409
    too (disconnect first - there is nothing to replace mid-flow).
    """
    if ghc.env_token():
        raise HTTPException(status_code=409, detail=ghc.ENV_HINT)
    if doc and (doc.get("token_enc") or doc.get("token")):
        method = doc.get("auth_method") or "pat"
        if wanted == "pat" and method == "pat":
            return
        label = "OAuth" if method == "oauth" else "a personal access token"
        raise HTTPException(status_code=409, detail=f"GitHub is already connected with {label} - disconnect it first")
    if wanted == "pat" and ghc.pending_public(doc):
        raise HTTPException(status_code=409, detail="An OAuth sign-in is in progress - finish or cancel it first")


@router.put("/github/token")
async def put_token(body: TokenBody):
    token = body.token.strip()
    if not ghc.TOKEN_RE.match(token):
        raise HTTPException(status_code=422, detail="That does not look like a GitHub token (20-255 letters, digits, '_' or '-')")
    _exclusive(await ghc.get_doc(default_db), "pat")
    try:
        result = await ghc.connect(default_db, token)
    except GitHubError as e:
        raise _http_error(e)
    resume_polling()
    return result


@router.delete("/github")
async def delete_github():
    if ghc.env_token():
        raise HTTPException(status_code=409, detail="GitHub is connected through R2A_GITHUB_TOKEN in backend/.env - "
                                                    "remove it there and restart the backend to disconnect")
    return await ghc.disconnect(default_db)


@router.put("/github/settings")
async def put_settings(body: GitHubSettings):
    if body.oauth_client_id is not None:
        cid = body.oauth_client_id.strip()
        if cid and not ghc.CLIENT_ID_RE.match(cid):
            raise HTTPException(status_code=422, detail="oauth_client_id must be 8-100 letters, digits, '.', '_' or '-'")
        await default_db.integrations.update_one({"_id": ghc.DOC_ID}, {"$set": {"oauth_client_id": cid}}, upsert=True)
    if body.auto_push is not None:
        values = {k: v for k, v in body.auto_push.model_dump().items() if v is not None}
        return await ghc.set_auto_push(default_db, values)
    return ghc.public(await ghc.get_doc(default_db))


# ------------------------------------------------------------------ OAuth device flow
DEVICE_GRANT = "urn:ietf:params:oauth:grant-type:device_code"
OAUTH_ERRORS = {
    "device_flow_disabled": "Device flow is disabled for this OAuth app - enable it in the app's settings on GitHub",
    "incorrect_client_credentials": "GitHub does not know this OAuth client ID - check GITHUB_OAUTH_CLIENT_ID",
    "unsupported_grant_type": "GitHub rejected the device-flow grant type",
    "incorrect_device_code": "GitHub rejected the device code - start again",
}


async def _oauth_post(path: str, data: dict) -> dict:
    try:
        async with httpx.AsyncClient(timeout=ghc.TIMEOUT) as client:
            resp = await client.post(f"{ghc.oauth_url()}{path}", data=data,
                                     headers={"Accept": "application/json", "User-Agent": "ROADMAP2ARENA"})
    except httpx.HTTPError as exc:
        raise HTTPException(status_code=502, detail=f"Could not reach GitHub at {ghc.oauth_url()} ({type(exc).__name__})")
    try:
        body = resp.json()
    except ValueError:
        body = {}
    if resp.status_code >= 500:
        raise HTTPException(status_code=502, detail=f"GitHub OAuth endpoint failed ({resp.status_code})")
    if resp.status_code in (401, 404):  # GitHub answers an unknown client ID with 404 Not Found
        body = {"error": "incorrect_client_credentials"}
    elif resp.status_code >= 400 and not body.get("error"):
        body = {"error": f"http_{resp.status_code}"}
    return body


@router.post("/github/oauth/start")
async def oauth_start():
    doc = await ghc.get_doc(default_db)
    _exclusive(doc, "oauth")
    try:
        ghc.require_key()
    except GitHubError as e:
        raise _http_error(e)
    cid, _ = ghc.oauth_client(doc)
    if not cid:
        raise HTTPException(status_code=409, detail="OAuth is not configured - set GITHUB_OAUTH_CLIENT_ID in backend/.env "
                                                    "or save an OAuth app client ID in Settings")
    body = await _oauth_post("/login/device/code", {"client_id": cid, "scope": "repo"})
    if body.get("error") or not body.get("device_code"):
        err = body.get("error", "unknown")
        raise HTTPException(status_code=422, detail=OAUTH_ERRORS.get(err, f"GitHub refused the device flow ({err}: "
                                                                          f"{body.get('error_description', '')})"))
    expires_in, interval = int(body.get("expires_in", 900)), int(body.get("interval", 5))
    ts = time.time()
    pending = {"device_code": body["device_code"], "user_code": body["user_code"],
               "verification_uri": body.get("verification_uri", "https://github.com/login/device"),
               "interval": interval, "expires_ts": ts + expires_in, "last_poll_ts": 0,
               "expires_at": datetime.fromtimestamp(ts + expires_in, timezone.utc).isoformat(timespec="seconds").replace("+00:00", "Z")}
    await default_db.integrations.update_one({"_id": ghc.DOC_ID}, {"$set": {"oauth_pending": pending}}, upsert=True)
    return ghc.pending_public({"oauth_pending": pending})


async def _clear_pending() -> None:
    await default_db.integrations.update_one({"_id": ghc.DOC_ID}, {"$unset": {"oauth_pending": ""}})


@router.post("/github/oauth/poll")
async def oauth_poll():
    """One exchange attempt; never calls GitHub more often than the interval it asked for."""
    doc = await ghc.get_doc(default_db)
    pending = (doc or {}).get("oauth_pending")
    if not pending:
        if ghc.public(doc)["connected"]:
            return {"status": "connected", "interval": None, "github": ghc.public(doc)}
        raise HTTPException(status_code=409, detail="No OAuth sign-in in progress - start one first")
    now = time.time()
    if pending["expires_ts"] < now:
        await _clear_pending()
        return {"status": "expired", "interval": None, "github": ghc.public(await ghc.get_doc(default_db))}
    if now - pending.get("last_poll_ts", 0) < pending["interval"] - 0.2:
        return {"status": "pending", "interval": pending["interval"], "github": ghc.public(doc)}
    await default_db.integrations.update_one({"_id": ghc.DOC_ID}, {"$set": {"oauth_pending.last_poll_ts": now}})
    cid, _ = ghc.oauth_client(doc)
    body = await _oauth_post("/login/oauth/access_token", {"client_id": cid, "device_code": pending["device_code"],
                                                           "grant_type": DEVICE_GRANT})
    token, err = body.get("access_token"), body.get("error")
    if token:
        scopes = [x.strip() for x in (body.get("scope") or "").split(",") if x.strip()]
        try:
            gh = await ghc.connect(default_db, token, method="oauth", scopes=scopes)
        except GitHubError as e:
            await _clear_pending()
            raise _http_error(e)
        logger.info("GitHub connected via OAuth device flow as %s", gh["username"])
        resume_polling()
        return {"status": "connected", "interval": None, "github": gh}
    if err == "authorization_pending":
        return {"status": "pending", "interval": pending["interval"], "github": ghc.public(doc)}
    if err == "slow_down":
        interval = int(body.get("interval") or pending["interval"] + 5)
        await default_db.integrations.update_one({"_id": ghc.DOC_ID}, {"$set": {"oauth_pending.interval": interval}})
        return {"status": "slow_down", "interval": interval, "github": ghc.public(await ghc.get_doc(default_db))}
    await _clear_pending()
    status = {"expired_token": "expired", "access_denied": "denied"}.get(err)
    if status:
        return {"status": status, "interval": None, "github": ghc.public(await ghc.get_doc(default_db))}
    raise HTTPException(status_code=422, detail=OAUTH_ERRORS.get(err, f"GitHub OAuth failed ({err}: {body.get('error_description', '')})"))


@router.post("/github/oauth/cancel")
async def oauth_cancel():
    await _clear_pending()
    return ghc.public(await ghc.get_doc(default_db))


@router.get("/github/repos")
async def list_repos(q: str = Query("", max_length=100)):
    token = await _token_or_409(default_db)
    items, truncated = [], False
    try:
        async with GitHub(token) as gh:
            for page in range(1, REPO_PAGES + 1):
                r = await gh.request("GET", "/user/repos", "list your repositories", params={
                    "per_page": 100, "page": page, "sort": "updated",
                    "affiliation": "owner,collaborator,organization_member"})
                batch = r.json()
                items.extend(batch)
                if len(batch) < 100:
                    break
            else:
                truncated = True
    except GitHubError as e:
        raise _http_error(e)
    needle = q.strip().lower()
    out = [_repo_summary(r) for r in items if not needle or needle in (r.get("full_name") or "").lower()]
    return {"items": out, "total": len(out), "truncated": truncated}


@router.get("/jobs/{job_id}/github")
async def job_github(job_id: str):
    job = await default_db.jobs.find_one({"id": job_id}, {"_id": 0, "log": 0})
    if not job:
        raise HTTPException(status_code=404, detail=f"Job {job_id} not found")
    steps = await default_db.steps.find({"job_id": job_id}, {"_id": 0, "index": 1, "title": 1, "status": 1}).sort("index", 1).to_list(None)
    gh = ghc.public(await ghc.get_doc(default_db))
    watches = await default_db.github_watches.find({"job_id": job_id}, {"_id": 0, "etags": 0}).to_list(50)
    return {"job_id": job_id, "connected": gh["connected"], "username": gh["username"],
            "defaults": defaults_for(job, steps), "last_push": job.get("github"), "watches": watches}


@router.post("/jobs/{job_id}/github/push")
async def push(job_id: str, body: PushRequest):
    try:
        return await push_job(default_db, job_id, body)
    except GitHubError as e:
        await append_log(default_db, job_id, "warn", f"GitHub: push failed - {e.message}")
        raise _http_error(e)


# ------------------------------------------------------------------ notifications + watcher
async def _notify(db, event: str, job_id: str | None, message: str, link: str | None) -> None:
    try:
        job = await db.jobs.find_one({"id": job_id}, {"_id": 0, "log": 0}) if job_id else None
        await notifier.notify(db, event, job, message=message, link=link)
    except Exception:  # noqa: BLE001 - notifications never break GitHub work
        logger.exception("GitHub notification %s failed", event)


_poll_lock = asyncio.Lock()
_poller: asyncio.Task | None = None
_wake: asyncio.Event | None = None
_paused_until = 0.0
_pause_reason: str | None = None


def _wake_poller() -> None:
    if _wake is not None:
        _wake.set()


def resume_polling() -> None:
    """A new token: lift an auth/rate-limit pause and poll soon."""
    global _paused_until, _pause_reason
    _paused_until, _pause_reason = 0.0, None
    _wake_poller()


async def upsert_watch(db, job_id: str, full_name: str, html_url: str, branch: str, head: str, pr: dict | None) -> None:
    now = datetime.now(timezone.utc)
    await db.github_watches.update_one(
        {"job_id": job_id, "full_name": full_name, "branch": branch},
        {"$set": {"html_url": html_url, "head_sha": head, "pr_number": pr["number"] if pr else None, "active": True,
                  "etags": {}, "state": {"pr_state": pr.get("state", "open") if pr else None, "ci": None, "src": {}},
                  "last_error": None, "pushed_at": now.isoformat(), "expires_at": (now + timedelta(days=WATCH_DAYS)).isoformat(),
                  "updated_at": now_iso()},
         "$setOnInsert": {"created_at": now_iso()}}, upsert=True)
    _wake_poller()


FAILED = {"failure", "timed_out", "action_required", "cancelled", "startup_failure", "error"}


def ci_state(src: dict) -> str:
    """Aggregate {'status': combined state, 'status_count', 'checks': [conclusion|None]} into none|pending|success|failure."""
    states = []
    if src.get("status_count"):
        states.append(src.get("status"))
    states += [("pending" if c is None else "failure" if c in FAILED else "success") for c in src.get("checks") or []]
    if not states:
        return "none"
    if "failure" in states or "error" in states:
        return "failure"
    return "pending" if "pending" in states else "success"


async def poll_watch(gh: GitHub, w: dict) -> list[tuple[str, str, str]]:
    """Poll one watch with conditional requests; returns [(event, message, link)] and updates w in place."""
    full = w["full_name"]
    base, et, st, events = f"/repos/{full}", dict(w.get("etags") or {}), dict(w.get("state") or {}), []
    html = w.get("html_url") or f"https://github.com/{full}"
    changed, data, et["branch"] = await gh.get_cond(f"{base}/branches/{GitHub.ref(w['branch'])}", et.get("branch"),
                                                    f"read branch {w['branch']} of {full}")
    if changed and data and data.get("commit", {}).get("sha") and data["commit"]["sha"] != w["head_sha"]:
        w["head_sha"] = data["commit"]["sha"]
        st.update(ci=None, src={})
        for k in ("status", "checks_api", "actions_api"):
            et.pop(k, None)
        events.append(("github_pushed", f"New commits on {full}:{w['branch']} ({w['head_sha'][:7]})",
                       f"{html}/commit/{w['head_sha']}"))
    if w.get("pr_number") and st.get("pr_state") not in ("merged", "closed"):
        changed, pr, et["pr"] = await gh.get_cond(f"{base}/pulls/{w['pr_number']}", et.get("pr"),
                                                  f"read pull request #{w['pr_number']} of {full}")
        if changed and pr:
            new = "merged" if pr.get("merged") else pr.get("state")  # `merged`, never merge_commit_sha (gone in 2026-03-10)
            if new != st.get("pr_state"):
                st["pr_state"] = new
                if new == "merged":
                    events.append(("github_pr_merged", f"PR #{w['pr_number']} merged in {full}", pr.get("html_url")))
                elif new == "closed":
                    events.append(("github_pr_closed", f"PR #{w['pr_number']} in {full} closed without merging",
                                   pr.get("html_url")))
    if st.get("ci") not in ("success", "failure"):
        src, sha = dict(st.get("src") or {}), w["head_sha"]
        changed, data, et["status"] = await gh.get_cond(f"{base}/commits/{sha}/status", et.get("status"),
                                                        "read the commit status")
        if changed and data:
            src.update(status=data.get("state"), status_count=data.get("total_count", 0))
        for api, path, key, params in (("checks_api", f"{base}/commits/{sha}/check-runs", "check_runs", {"per_page": 100}),
                                       ("actions_api", f"{base}/actions/runs", "workflow_runs", {"head_sha": sha, "per_page": 50})):
            if st.get(api) == "unavailable":
                continue
            try:
                changed, data, et[api] = await gh.get_cond(path, et.get(api), "read CI results", params)
            except GitHubError as e:
                if e.kind not in ("forbidden", "not_found"):
                    raise
                st[api] = "unavailable"  # e.g. a fine-grained PAT without Checks access: use Actions runs instead
                continue
            if changed and data:
                src["checks"] = [r.get("conclusion") if r.get("status") == "completed" else None for r in data.get(key, [])]
            if src.get("checks"):
                break  # check runs already include GitHub Actions; workflow runs are only the fallback
        st["src"], new = src, ci_state(src)
        if new in ("success", "failure") and new != st.get("ci"):
            ok = new == "success"
            events.append(("github_checks_passed" if ok else "github_checks_failed",
                           f"Checks {'passed' if ok else 'failed'} on {full}:{w['branch']} ({sha[:7]})", f"{html}/commit/{sha}"))
        st["ci"] = new
    w["etags"], w["state"] = et, st
    now = datetime.now(timezone.utc)
    pr_done = not w.get("pr_number") or st.get("pr_state") in ("merged", "closed")
    fresh = datetime.fromisoformat(w["pushed_at"]) > now - NO_CI_GRACE
    ci_done = st.get("ci") in ("success", "failure") or (st.get("ci") == "none" and not fresh)  # CI may start late
    w["active"] = datetime.fromisoformat(w["expires_at"]) > now and not (pr_done and ci_done)
    return events


async def poll_once(db=None) -> dict:
    """One pass over the active watches, serially (GitHub asks integrations not to send concurrent requests)."""
    global _paused_until, _pause_reason
    db = db if db is not None else default_db
    if time.time() < _paused_until:
        return {"skipped": _pause_reason or "paused", "resume_in": int(_paused_until - time.time()), "watches": 0,
                "notifications": 0}
    token = await ghc.get_token(db)
    if not token:
        return {"skipped": "not_connected", "watches": 0, "notifications": 0}
    async with _poll_lock:
        watches = await db.github_watches.find({"active": True}).sort("updated_at", -1).to_list(100)
        sent, polled, now = 0, 0, datetime.now(timezone.utc)
        async with GitHub(token) as gh:
            for w in watches:
                if datetime.fromisoformat(w["expires_at"]) < now:
                    await db.github_watches.update_one({"_id": w["_id"]}, {"$set": {"active": False}})
                    continue
                try:
                    events, err = await poll_watch(gh, w), None
                except GitHubError as e:
                    if e.kind in ("rate_limited", "auth"):
                        _paused_until = time.time() + ((e.retry_after or 60) if e.kind == "rate_limited" else 600)
                        _pause_reason = e.kind
                        logger.warning("GitHub polling paused (%s): %s", e.kind, e.message)
                        await db.github_watches.update_one({"_id": w["_id"]}, {"$set": {"last_error": e.message}})
                        break
                    events, err = [], e.message
                polled += 1
                await db.github_watches.update_one({"_id": w["_id"]}, {"$set": {
                    "head_sha": w["head_sha"], "etags": w.get("etags", {}), "state": w.get("state", {}),
                    "active": w.get("active", True), "last_error": err, "last_polled_at": now_iso()}})
                for event, message, link in events:
                    await _notify(db, event, w["job_id"], message, link)
                    sent += 1
            remaining, reset = gh.rate.get("remaining"), gh.rate.get("reset")
            if remaining is not None and remaining.isdigit() and int(remaining) < RATE_FLOOR and (reset or "").isdigit():
                _paused_until, _pause_reason = float(reset), "rate_low"
                logger.warning("GitHub polling paused until the rate limit resets (%s calls left)", remaining)
    return {"watches": polled, "notifications": sent}


async def _loop() -> None:
    while True:
        try:
            await poll_once()
        except asyncio.CancelledError:
            raise
        except Exception:  # noqa: BLE001 - keep polling
            logger.exception("GitHub poll failed")
        try:
            await asyncio.wait_for(_wake.wait(), timeout=poll_seconds())
        except asyncio.TimeoutError:
            pass
        _wake.clear()


def start_poller() -> None:
    global _poller, _wake
    if _poller is None or _poller.done():
        _wake = asyncio.Event()
        _poller = asyncio.create_task(_loop(), name="github-poller")


async def stop_poller() -> None:
    global _poller
    if _poller:
        _poller.cancel()
        try:
            await _poller
        except asyncio.CancelledError:
            pass
        _poller = None


async def ensure_indexes(db) -> None:
    await db.github_watches.create_index([("job_id", 1), ("full_name", 1), ("branch", 1)], unique=True)
    await db.github_watches.create_index([("active", 1)])


async def on_delete(db, job_id: str) -> None:
    """deletion_routes.on_delete hook: stop watching a deleted job (remote repositories are never touched)."""
    await db.github_watches.delete_many({"job_id": job_id})


@router.get("/github/watches")
async def list_watches():
    items = await default_db.github_watches.find({}, {"_id": 0, "etags": 0}).sort("updated_at", -1).to_list(200)
    paused = max(0, int(_paused_until - time.time()))
    return {"items": items, "poll_seconds": poll_seconds(), "paused_for": paused, "pause_reason": _pause_reason if paused else None}


@router.post("/github/poll")
async def poll_now():
    try:
        return await poll_once()
    except GitHubError as e:
        raise _http_error(e)
