"""Local stand-in for arena2api used in tests (NOT the real gateway).

Serves POST /v1/chat/completions in OpenAI format with canned fenced code
blocks. The response depends on how many user turns are in the request
history, so step N of a job gets canned reply N (cycled).

Magic model names:
  stub-503   -> HTTP 503 (simulates arena2api without a session token)
  stub-slow  -> sleeps STUB_SLOW_SECONDS (default 5) per call, for 409 testing
  stub-503-at-N -> HTTP 503 on the N-th user turn only

Run: /app/venv/bin/uvicorn tests.arena_stub:app --host 127.0.0.1 --port 9090
(from /app/backend).
"""
from __future__ import annotations

import asyncio
import os
import time
import uuid

from fastapi import FastAPI, Request
from fastapi.responses import JSONResponse

FENCE = "```"
SLOW_SECONDS = float(os.environ.get("STUB_SLOW_SECONDS", "5"))

app = FastAPI(title="arena2api stub")


def _turn_1() -> str:
    return f"""Setting up the package.

{FENCE}python:app/main.py
from fastapi import FastAPI

app = FastAPI()


@app.get("/health")
def health():
    return {{"status": "ok"}}
{FENCE}

{FENCE}toml
# filename: pyproject.toml
[project]
name = "stub-project"
version = "0.1.0"
{FENCE}

Run it with:

{FENCE}bash
uvicorn app.main:app --reload
{FENCE}
"""


def _turn_2() -> str:
    return f"""Adding models and a helper. Two paths below are intentionally unsafe for ZIP tests.

{FENCE}python:app/models.py
from pydantic import BaseModel


class Item(BaseModel):
    id: int
    name: str
{FENCE}

{FENCE}python:../evil.py
print("this must never be written outside the project")
{FENCE}

{FENCE}python:/abs/x.py
print("absolute path - should be stored as abs/x.py in the ZIP")
{FENCE}
"""


def _turn_3() -> str:
    return f"""Updating main.py to include the router and adding docs.

{FENCE}python:app/main.py
from fastapi import FastAPI

from app.models import Item

app = FastAPI()


@app.get("/health")
def health():
    return {{"status": "ok"}}


@app.get("/items/{{item_id}}")
def read_item(item_id: int) -> Item:
    return Item(id=item_id, name="example")
{FENCE}

{FENCE}markdown
<!-- path: README.md -->
# Stub project

Generated by the arena2api stub.
{FENCE}
"""


TURNS = [_turn_1, _turn_2, _turn_3]


def _completion(model: str, content: str, prompt_chars: int) -> dict:
    return {
        "id": f"chatcmpl-{uuid.uuid4().hex[:12]}",
        "object": "chat.completion",
        "created": int(time.time()),
        "model": model,
        "choices": [{
            "index": 0,
            "message": {"role": "assistant", "content": content},
            "finish_reason": "stop",
        }],
        "usage": {"prompt_tokens": prompt_chars // 4, "completion_tokens": len(content) // 4,
                  "total_tokens": (prompt_chars + len(content)) // 4},
    }


def _error(status: int, message: str) -> JSONResponse:
    return JSONResponse(status_code=status, content={"error": {"message": message, "type": "stub_error", "code": status}})


@app.get("/v1/models")
async def models():
    return {"object": "list", "data": [{"id": m, "object": "model"} for m in ("gpt-4o", "stub-503", "stub-slow")]}


@app.post("/v1/chat/completions")
async def chat(request: Request):
    body = await request.json()
    model = body.get("model", "")
    messages = body.get("messages", [])
    turn = sum(1 for m in messages if m.get("role") == "user")
    if model == "stub-503":
        return _error(503, "no upstream session token available")
    if model.startswith("stub-503-at-") and model.rsplit("-", 1)[-1].isdigit() and turn == int(model.rsplit("-", 1)[-1]):
        return _error(503, "no upstream session token available")
    if model == "stub-slow":
        await asyncio.sleep(SLOW_SECONDS)
    content = TURNS[(max(turn, 1) - 1) % len(TURNS)]()
    prompt_chars = sum(len(m.get("content") or "") for m in messages)
    return _completion(model, content, prompt_chars)
