#!/usr/bin/env python3
"""Make sure backend/.env has R2A_SECRET_KEY (the Fernet key that encrypts the stored GitHub token).

    ./venv/bin/python scripts/ensure_secret_key.py [path/to/backend/.env]

- Values are read exactly like the backend reads them (python-dotenv, last assignment wins).
- Effective key non-empty -> the file is left byte-for-byte unchanged (only chmod 600).
- A non-empty key is NEVER replaced: replacing it would make a saved GitHub token unreadable.
  If a non-empty key is shadowed by a later empty `R2A_SECRET_KEY=` line, the later empty
  line(s) are removed so the existing key takes effect again; no new key is generated.
- No key at all, or only empty assignments -> generate one. The first empty assignment is
  filled in place (later empty duplicates are dropped), otherwise the key is appended.
- Creates the file (and its directory) if missing, keeps every other line as is, chmod 600.
- Never prints the key. Exit 0 on success (generated or kept), 1 on error.
Called by setup.sh after the backend venv is installed (needs `cryptography` and `python-dotenv`).
"""
from __future__ import annotations

import io
import os
import re
import sys
import tempfile

NAME = "R2A_SECRET_KEY"
# Lines that assign NAME (optionally `export NAME=`), as python-dotenv accepts them.
LINE_RE = re.compile(rf"^\s*(?:export\s+)?{NAME}\s*=")


def _line_value(line: str) -> str:
    """Value of a single assignment line, parsed by python-dotenv itself (quotes, ` #` comments)."""
    from dotenv import dotenv_values
    return (dotenv_values(stream=io.StringIO(line), interpolate=False).get(NAME) or "").strip()


def _write(path: str, text: str) -> None:
    d = os.path.dirname(os.path.abspath(path))
    os.makedirs(d, exist_ok=True)
    fd, tmp = tempfile.mkstemp(dir=d, prefix=".env.", suffix=".tmp")  # mkstemp => mode 600
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="") as f:
            f.write(text)
        os.replace(tmp, path)
    except BaseException:
        if os.path.exists(tmp):
            os.unlink(tmp)
        raise


def ensure(path: str) -> str:
    """Returns "kept", "unshadowed" or "generated"."""
    from dotenv import dotenv_values

    exists = os.path.exists(path)
    if exists:
        effective = (dotenv_values(path, interpolate=False).get(NAME) or "").strip()
        if effective:
            os.chmod(path, 0o600)
            return "kept"
        with open(path, encoding="utf-8", newline="") as f:
            text = f.read()
    else:
        text = ""

    lines = text.splitlines(keepends=True)
    hits = [i for i, l in enumerate(lines) if LINE_RE.match(l)]
    nonempty = [i for i in hits if _line_value(lines[i])]

    if nonempty:
        # A real key exists but a later empty assignment overrides it: drop the later empty ones.
        last = nonempty[-1]
        for i in reversed([i for i in hits if i > last]):
            del lines[i]
        _write(path, "".join(lines))
        os.chmod(path, 0o600)
        return "unshadowed"

    from cryptography.fernet import Fernet
    key = Fernet.generate_key().decode()
    if hits:  # only empty assignments: fill the first in place, drop later empty duplicates
        eol = "\r\n" if lines[hits[0]].endswith("\r\n") else "\n"
        lines[hits[0]] = f"{NAME}={key}{eol}"
        for i in reversed(hits[1:]):
            del lines[i]
    else:
        if lines and not lines[-1].endswith("\n"):
            lines[-1] += "\n"
        lines.append("# Fernet key that encrypts the stored GitHub token (generated by setup.sh). Keep it:\n"
                     "# changing or losing it means reconnecting GitHub in Settings.\n")
        lines.append(f"{NAME}={key}\n")
    _write(path, "".join(lines))
    os.chmod(path, 0o600)
    return "generated"


def _warn_if_invalid(path: str) -> None:
    """Warn (without printing the key) when the kept key is not a valid Fernet key."""
    try:
        from cryptography.fernet import Fernet
        from dotenv import dotenv_values
        Fernet((dotenv_values(path, interpolate=False).get(NAME) or "").strip().encode())
    except ImportError:
        pass
    except Exception:  # noqa: BLE001
        print(f"WARNING: {path}: {NAME} is set but is not a valid Fernet key; it was left unchanged. "
              "GitHub cannot be connected until it is fixed.", file=sys.stderr)


def main() -> int:
    path = sys.argv[1] if len(sys.argv) > 1 else os.path.join(
        os.path.dirname(os.path.abspath(__file__)), "..", "backend", ".env")
    path = os.path.normpath(path)
    try:
        result = ensure(path)
    except ImportError as e:
        print(f"ERROR: {e.name or e} is not installed in {sys.executable} - "
              "run pip install -r backend/requirements.txt", file=sys.stderr)
        return 1
    except (OSError, UnicodeDecodeError) as e:
        print(f"ERROR: could not update {path}: {e}", file=sys.stderr)
        return 1
    if result == "kept":
        print(f"{path}: {NAME} already set (kept - never overwritten)")
        _warn_if_invalid(path)
    elif result == "unshadowed":
        print(f"{path}: {NAME} already set (kept); removed later empty {NAME}= line(s) that overrode it")
        _warn_if_invalid(path)
    else:
        print(f"{path}: {NAME} generated (GitHub token encryption). Back up this file: "
              "losing or changing the key means reconnecting GitHub.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
